### ISSUE TITLE
"yarn build" fails (spectacularly)

### ISSUE THREAD

**Issue by mgleavitt** [dead-in-the-water/ditw#1]
Errors reported to console:

ERROR in ./src/client/assets/styles/styles.scss
Module build failed: Error
    at /Users/mgleavitt/dev/ditw/node_modules/webpack/lib/NormalModule.js:137:35
    at /Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at iterateNormalLoaders (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at context.callback (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/mgleavitt/dev/ditw/node_modules/postcss-loader/index.js:100:13
 @ ./src/client/scripts/production.js 5:0-29

ERROR in ./src/client/assets/styles/bootstrap.min.css
Module build failed: Error
    at /Users/mgleavitt/dev/ditw/node_modules/webpack/lib/NormalModule.js:137:35
    at /Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at iterateNormalLoaders (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at context.callback (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/mgleavitt/dev/ditw/node_modules/postcss-loader/index.js:100:13
 @ ./src/client/assets/javascripts/app/index.js 15:0-34
 @ ./src/client/scripts/production.js

ERROR in ./src/client/assets/javascripts/features/homePage/homePageView.scss
Module build failed: Error
    at /Users/mgleavitt/dev/ditw/node_modules/webpack/lib/NormalModule.js:137:35
    at /Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at iterateNormalLoaders (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at context.callback (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/mgleavitt/dev/ditw/node_modules/postcss-loader/index.js:100:13
 @ ./src/client/assets/javascripts/features/homePage/homePageView.js 36:0-29
 @ ./src/client/assets/javascripts/app/routes.js
 @ ./src/client/assets/javascripts/app/Root.js
 @ ./src/client/assets/javascripts/app/index.js
 @ ./src/client/scripts/production.js

ERROR in ./src/client/assets/javascripts/features/players/components/PlayerTableApp.scss
Module build failed: Error
    at /Users/mgleavitt/dev/ditw/node_modules/webpack/lib/NormalModule.js:137:35
    at /Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at iterateNormalLoaders (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at context.callback (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/mgleavitt/dev/ditw/node_modules/postcss-loader/index.js:100:13
 @ ./src/client/assets/javascripts/features/players/components/PlayersView.js 21:0-31
 @ ./src/client/assets/javascripts/app/routes.js
 @ ./src/client/assets/javascripts/app/Root.js
 @ ./src/client/assets/javascripts/app/index.js
 @ ./src/client/scripts/production.js

ERROR in ./src/client/assets/javascripts/features/newGame/gameTable.scss
Module build failed: Error
    at /Users/mgleavitt/dev/ditw/node_modules/webpack/lib/NormalModule.js:137:35
    at /Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at iterateNormalLoaders (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at context.callback (/Users/mgleavitt/dev/ditw/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/mgleavitt/dev/ditw/node_modules/postcss-loader/index.js:100:13
 @ ./src/client/assets/javascripts/features/newGame/newGameView.js 31:0-26
 @ ./src/client/assets/javascripts/app/routes.js
 @ ./src/client/assets/javascripts/app/Root.js
 @ ./src/client/assets/javascripts/app/index.js
 @ ./src/client/scripts/production.js
Child extract-text-webpack-plugin:
        + 1 hidden modules
    
    ERROR in ./~/css-loader?{"sourceMap":true}!./~/postcss-loader!./~/sass-loader?{"outputStyle":"compressed"}!./src/client/assets/styles/styles.scss
    Module build failed: Error: ENOENT: no such file or directory, open '/Users/mgleavitt/dev/ditw/node_modules/svgo/lib/svgo/../../.svgo.yml'
        at Object.fs.openSync (fs.js:582:18)
        at Object.fs.readFileSync (fs.js:489:33)
        at module.exports (/Users/mgleavitt/dev/ditw/node_modules/svgo/lib/svgo/config.js:31:48)
        at new module.exports (/Users/mgleavitt/dev/ditw/node_modules/svgo/lib/svgo.js:21:19)
        at /Users/mgleavitt/dev/ditw/node_modules/postcss-svgo/dist/index.js:95:16
        at Object.creator [as postcssSvgo] (/Users/mgleavitt/dev/ditw/node_modules/postcss/lib/postcss.js:150:35)
        at /Users/mgleavitt/dev/ditw/node_modules/cssnano/dist/index.js:295:40
        at Array.forEach (native)
        at /Users/mgleavitt/dev/ditw/node_modules/cssnano/dist/index.js:282:29
        at creator (/Users/mgleavitt/dev/ditw/node_modules/postcss/lib/postcss.js:150:35)
        at processCss (/Users/mgleavitt/dev/ditw/node_modules/css-loader/lib/processCss.js:186:16)
        at Object.module.exports (/Users/mgleavitt/dev/ditw/node_modules/css-loader/lib/loader.js:24:2)
Child extract-text-webpack-plugin:
        + 1 hidden modules
    
    ERROR in ./~/css-loader!./~/postcss-loader!./src/client/assets/styles/bootstrap.min.css
    Module build failed: Error: ENOENT: no such file or directory, open '/Users/mgleavitt/dev/ditw/node_modules/svgo/lib/svgo/../../.svgo.yml'
        at Object.fs.openSync (fs.js:582:18)
        at Object.fs.readFileSync (fs.js:489:33)
        at module.exports (/Users/mgleavitt/dev/ditw/node_modules/svgo/lib/svgo/config.js:31:48)
        at new module.exports (/Users/mgleavitt/dev/ditw/node_modules/svgo/lib/svgo.js:21:19)
        at /Users/mgleavitt/dev/ditw/node_modules/postcss-svgo/dist/index.js:95:16
        at Object.creator [as postcssSvgo] (/Users/mgleavitt/dev/ditw/node_modules/postcss/lib/postcss.js:150:35)
        at /Users/mgleavitt/dev/ditw/node_modules/cssnano/dist/index.js:295:40
        at Array.forEach (native)
        at /Users/mgleavitt/dev/ditw/node_modules/cssnano/dist/index.js:282:29
        at creator (/Users/mgleavitt/dev/ditw/node_modules/postcss/lib/postcss.js:150:35)
        at processCss (/Users/mgleavitt/dev/ditw/node_modules/css-loader/lib/processCss.js:186:16)
        at Object.module.exports (/Users/mgleavitt/dev/ditw/node_modules/css-loader/lib/loader.js:24:2)
Child extract-text-webpack-plugin:
        + 1 hidden modules
    
    ERROR in ./~/css-loader?{"sourceMap":true}!./~/postcss-loader!./~/sass-loader?{"outputStyle":"compressed"}!./src/client/assets/javascripts/features/homePage/homePageView.scss
    Module build failed: Error: ENOENT: no such file or directory, open '/Users/mgleavitt/dev/ditw/node_modules/svgo/lib/svgo/../../.svgo.yml'
        at Object.fs.openSync (fs.js:582:18)
        at Object.fs.readFileSync (fs.js:489:33)
        at module.exports (/Users/mgleavitt/dev/ditw/node_modules/svgo/lib/svgo/config.js:31:48)
        at new module.exports (/Users/mgleavitt/dev/ditw/node_modules/svgo/lib/svgo.js:21:19)
        at /Users/mgleavitt/dev/ditw/node_modules/postcss-svgo/dist/index.js:95:16
        at Object.creator [as postcssSvgo] (/Users/mgleavitt/dev/ditw/node_modules/postcss/lib/postcss.js:150:35)
        at /Users/mgleavitt/dev/ditw/node_modules/cssnano/dist/index.js:295:40
        at Array.forEach (native)
        at /Users/mgleavitt/dev/ditw/node_modules/cssnano/dist/index.js:282:29
        at creator (/Users/mgleavitt/dev/ditw/node_modules/postcss/lib/postcss.js:150:35)
        at processCss (/Users/mgleavitt/dev/ditw/node_modules/css-loader/lib/processCss.js:186:16)
        at Object.module.exports (/Users/mgleavitt/dev/ditw/node_modules/css-loader/lib/loader.js:24:2)
Child extract-text-webpack-plugin:
        + 1 hidden modules
    
    ERROR in ./~/css-loader?{"sourceMap":true}!./~/postcss-loader!./~/sass-loader?{"outputStyle":"compressed"}!./src/client/assets/javascripts/features/players/components/PlayerTableApp.scss
    Module build failed: Error: ENOENT: no such file or directory, open '/Users/mgleavitt/dev/ditw/node_modules/svgo/lib/svgo/../../.svgo.yml'
        at Object.fs.openSync (fs.js:582:18)
        at Object.fs.readFileSync (fs.js:489:33)
        at module.exports (/Users/mgleavitt/dev/ditw/node_modules/svgo/lib/svgo/config.js:31:48)
        at new module.exports (/Users/mgleavitt/dev/ditw/node_modules/svgo/lib/svgo.js:21:19)
        at /Users/mgleavitt/dev/ditw/node_modules/postcss-svgo/dist/index.js:95:16
        at Object.creator [as postcssSvgo] (/Users/mgleavitt/dev/ditw/node_modules/postcss/lib/postcss.js:150:35)
        at /Users/mgleavitt/dev/ditw/node_modules/cssnano/dist/index.js:295:40
        at Array.forEach (native)
        at /Users/mgleavitt/dev/ditw/node_modules/cssnano/dist/index.js:282:29
        at creator (/Users/mgleavitt/dev/ditw/node_modules/postcss/lib/postcss.js:150:35)
        at processCss (/Users/mgleavitt/dev/ditw/node_modules/css-loader/lib/processCss.js:186:16)
        at Object.module.exports (/Users/mgleavitt/dev/ditw/node_modules/css-loader/lib/loader.js:24:2)
Child extract-text-webpack-plugin:
        + 1 hidden modules
    
    ERROR in ./~/css-loader?{"sourceMap":true}!./~/postcss-loader!./~/sass-loader?{"outputStyle":"compressed"}!./src/client/assets/javascripts/features/newGame/gameTable.scss
    Module build failed: Error: ENOENT: no such file or directory, open '/Users/mgleavitt/dev/ditw/node_modules/svgo/lib/svgo/../../.svgo.yml'
        at Object.fs.openSync (fs.js:582:18)
        at Object.fs.readFileSync (fs.js:489:33)
        at module.exports (/Users/mgleavitt/dev/ditw/node_modules/svgo/lib/svgo/config.js:31:48)
        at new module.exports (/Users/mgleavitt/dev/ditw/node_modules/svgo/lib/svgo.js:21:19)
        at /Users/mgleavitt/dev/ditw/node_modules/postcss-svgo/dist/index.js:95:16
        at Object.creator [as postcssSvgo] (/Users/mgleavitt/dev/ditw/node_modules/postcss/lib/postcss.js:150:35)
        at /Users/mgleavitt/dev/ditw/node_modules/cssnano/dist/index.js:295:40
        at Array.forEach (native)
        at /Users/mgleavitt/dev/ditw/node_modules/cssnano/dist/index.js:282:29
        at creator (/Users/mgleavitt/dev/ditw/node_modules/postcss/lib/postcss.js:150:35)
        at processCss (/Users/mgleavitt/dev/ditw/node_modules/css-loader/lib/processCss.js:186:16)
        at Object.module.exports (/Users/mgleavitt/dev/ditw/node_modules/css-loader/lib/loader.js:24:2)
error Command failed with exit code 2.

**Comment by danleavitt0** [comment]
Remove the .yarnclean file from the root directory, remove node_modules, yarn install, yarn build

**Comment by mgleavitt** [comment]
This appears to be caused by running 'yarn clean'
